# # Generated by Django 4.2.2 on 2023-11-21 17:04

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     initial = True

#     dependencies = [
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='vendor',
#             fields=[
#                 ('vendor_code', models.CharField(primary_key=True, serialize=False)),
#                 ('name', models.CharField(max_length=25)),
#                 ('contact_details', models.TextField()),
#                 ('address', models.TextField()),
#                 ('on_time_delivery_rate', models.FloatField()),
#                 ('quality_rating_avg', models.FloatField()),
#                 ('average_response_time', models.FloatField()),
#                 ('fulfillment_rate', models.FloatField()),
#             ],
#         ),
#     ]


# Generated by Django 4.2.2 on 2023-11-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.CharField(primary_key=True, max_length=50, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_details', models.TextField()),
                ('address', models.TextField()),
                ('on_time_delivery_rate', models.FloatField(default=0.0)),
                ('quality_rating_avg', models.FloatField(default=0.0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('fulfillment_rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
